### ISSUE TITLE
Sostituire i forEach con map, filter e reduce

### ISSUE THREAD

**Issue by dinb79** [ANTREEM/a-tal-deg-proposte#17]
@Sbax

**Comment by Sbax** [comment]
Spesso il forEach è utilizzato impropriamente ed esistono metodi migliori per sostituirlo, togliendo molti dei problemi che introduce.
In questo breve talk vedremo una brevissima introduzione alla programmazione funzionale in js, con l'utilizzo di map, filter e reduce

**Comment by Sbax** [comment]
Si terrà il 22/09/2020 alle 18, sarà possibile seguire l'incontro su [meet](https://meet.google.com/euk-hjmg-dac?authuser=2&hs=122&ijlm=1600075256981)
