### ISSUE TITLE
A real hack of today, not yesterday + APT + Malware

### ISSUE THREAD

**Issue by ludovicoloreti** [ANTREEM/a-tal-deg-proposte#23]
_Titolo probabilmente in via di cambiamento per ora lo lascio così, se avete proposte scrivete._

### Topic

Tutti gli hack realtime che vediamo di solito ( e di conferenze ne ho fatte e non poche ) sono in perfetto stile anni 90.. sql injection e / o xss.
Ebbene vorrei sfatare questo mito, e realizzare INSIEME a voi, un hack in pieno stile contemporaneo. In breve, un hack di "oggi".
Vorrei affrontare la Cyber Kill Chain per farvi capire come oggi i gruppi APT (advanced persistent threat actors) agiscono, realizzare uno hack facsimile e, infine affrontare quelli che vengono definiti malware, o più semplicemente hack automatizzati (che poi neanche tanto). 
Quindi capire come ragionano, come si mettono li a programmare volendo anche in linguaggi da noi ben conosciuti (ci sono stati vari dropper in javascript) per raggiungere uno scopo e, eventualmente capire anche quale sarebbe questo scopo.

Keywords:
hacking, APT, malware, ransomware, backdoor, C2 (o C&C), Cyber Kill Chain

**Comment by MaxArt2501** [comment]
Qui il materiale:
https://drive.google.com/drive/folders/1S1t4ds3eM9krOrM_urb871DC1eRunvTm
