### ISSUE TITLE
FE security, is it real?

### ISSUE THREAD

**Issue by ludovicoloreti** [ANTREEM/a-tal-deg-proposte#24]
Vorrei affrontare un piccolo talk anche con botta e risposta riguardante la sicurezza a Frontend, perché ci dovrebbe interessare pur non vendendo al cliente qualcosa come "sicuro" e, soprattutto:

ma serve davvero? O basta il backend?

**Comment by MaxArt2501** [comment]
È stata inclusa con un'altra sessione
